name: Build and Push

on:
  # push:
  #   branches:
  #     - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - name : display infomation(only pull req)
        run: |
          echo '1. '${{ github.head_ref }}
          echo '2. '${{ github.base_ref }}
        shell: bash -xe {0}

      - name : checkout base-branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name : read base-branch
        run : |
          cat ./diff-test/test.txt

      - name : checkout head-branch
        uses: actions/checkout@v3

      - name : read head-branch
        run : |
          cat ./diff-test/test.txt

      # - name : vars
      #   run : |
      #    echo "::set-output name=HOGEHOGE::12345"


