name: Diff check

on:
  # push:
  #   branches:
  #     - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - name : display infomation(only pull req)
        run: |
          echo '1. '${{ github.head_ref }}
          echo '2. '${{ github.base_ref }}
        shell: bash -xe {0}

      - name : checkout base-branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name : read base-branch
        id: base_branch
        run : |
          echo "base-branch : $(cat ./diff-test/tag_name.txt)"
          echo "::set-output name=tag_name::$(cat ./diff-test/tag_name.txt)"

      - name : checkout head-branch
        uses: actions/checkout@v3

      - name : read head-branch
        id: head_branch
        run : |
          echo "haed-branch : $(cat ./diff-test/tag_name.txt)"
          echo "::set-output name=tag_name::$(cat ./diff-test/tag_name.txt)"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Check Container image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
          BEFORE_IMAGE_TAG: ${{ steps.base_branch.outputs.tag_name }}
          AFTER_IMAGE_TAG: ${{ steps.head_branch.outputs.tag_name }}
        run: |
          docker create --name before-container $ECR_REGISTRY/$ECR_REPOSITORY:$BEFORE_IMAGE_TAG
          docker create --name after-container $ECR_REGISTRY/$ECR_REPOSITORY:$AFTER_IMAGE_TAG

          # beforeコードからcheck sumを作成
          # https://takuya-1st.hatenablog.jp/entry/20120711/1344804442
          docker cp before-container:/usr/share/nginx/html /tmp/diff

          find /tmp/diff -type f -exec md5sum {} \; > /tmp/check.md5sum
          rm -rf /tmp/diff

          # afterコードの差分比較
          docker cp after-container:/usr/share/nginx/html /tmp/diff

          find /tmp/diff -type f -exec md5sum {} -c /tmp/check.md5sum \;

        shell: bash -xe {0}

